#!/usr/bin/env node
// Regenerate .triage/<kind>/index.md from the YAML frontmatter of every results.md.
// Usage: node .claude/skills/triage/scripts/reindex.mjs [issues|prs]
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";

const kind = process.argv[2] ?? "prs";
if (kind !== "issues" && kind !== "prs") {
  console.error("usage: reindex.mjs [issues|prs]");
  process.exit(1);
}

const root = execFileSync("git", ["worktree", "list"], { encoding: "utf8" })
  .split("\n")[0]
  .split(" ")[0];
const dir = join(root, ".triage", kind);
if (!existsSync(dir)) {
  console.error(`no such directory: ${dir}`);
  process.exit(1);
}

function frontmatter(file) {
  const text = readFileSync(file, "utf8");
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) {
    return null;
  }
  const out = {};
  for (const line of match[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (kv) {
      out[kv[1]] = kv[2].trim().replace(/^["'](.*)["']$/, "$1");
    }
  }
  return out;
}

const rows = [];
for (const entry of readdirSync(dir, { withFileTypes: true })) {
  if (!entry.isDirectory() || !/^\d+$/.test(entry.name)) {
    continue;
  }
  const file = join(dir, entry.name, "results.md");
  if (!existsSync(file)) {
    continue;
  }
  const fm = frontmatter(file);
  rows.push({
    number: Number(entry.name),
    status: fm?.status ?? "unknown",
    verdict: fm?.verdict ?? "—",
    title: fm?.title ?? "",
    author: fm?.author ?? "",
  });
}
rows.sort((a, b) => b.number - a.number);

const noun = kind === "prs" ? "pull" : "issues";
const counts = {};
for (const row of rows) {
  counts[row.verdict] = (counts[row.verdict] ?? 0) + 1;
}
const done = rows.filter((row) => row.status === "done").length;

const lines = [
  `# ${kind === "prs" ? "PR" : "Issue"} triage index`,
  "",
  "Generated by `.claude/skills/triage/scripts/reindex.mjs` — do not hand-edit.",
  "",
  `${rows.length} written up, ${done} marked \`done\`.`,
  "",
  "## Verdicts",
  "",
  ...Object.entries(counts)
    .sort((a, b) => b[1] - a[1])
    .map(([verdict, n]) => `- \`${verdict}\` — ${n}`),
  "",
  "## Entries",
  "",
  "| # | Verdict | Status | Title | Author | Write-up |",
  "| --- | --- | --- | --- | --- | --- |",
  ...rows.map((row) => {
    const cells = [
      `[#${row.number}](https://github.com/Yoshinaga123/quiz/${noun}/${row.number})`,
      `\`${row.verdict}\``,
      row.status,
      row.title.replace(/\|/g, "\\|"),
      row.author ? `@${row.author}` : "",
      `[results.md](${row.number}/results.md)`,
    ];
    return `| ${cells.join(" | ")} |`;
  }),
  "",
];

writeFileSync(join(dir, "index.md"), lines.join("\n"));
console.log(`wrote ${join(dir, "index.md")} (${rows.length} entries)`);
