#!/usr/bin/env python3
"""Unit tests for replace-sync SQL generated by generate_migration.py."""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate_migration import build_down_sql, build_up_sql, delete_replaced_quiz_rows_sql


def sample_quiz(quiz_id: int) -> dict:
  return {
      'id': quiz_id,
      'section': 'Go',
      'title': 'title',
      'question': 'question',
      'code': None,
      'options': ['a', 'b'],
      'correctAnswerIndex': 0,
      'explanation': 'explanation',
      'source': 'https://example.com',
  }


class GenerateMigrationTests(unittest.TestCase):
  def test_replace_sync_deletes_deliveries_before_quizzes(self) -> None:
    sql = build_up_sql([sample_quiz(1), sample_quiz(2)], 'quizzes.json')
    delivery_delete = 'DELETE FROM push_deliveries WHERE NOT (quiz_id = ANY(ARRAY[1, 2]::bigint[]));'
    quiz_delete = 'DELETE FROM quizzes WHERE NOT (id = ANY(ARRAY[1, 2]::bigint[]));'
    self.assertIn(delivery_delete, sql)
    self.assertIn(quiz_delete, sql)
    self.assertLess(sql.index(delivery_delete), sql.index(quiz_delete))

  def test_empty_seed_clears_deliveries_then_quizzes(self) -> None:
    sql = build_up_sql([], 'quizzes.json')
    self.assertIn('DELETE FROM push_deliveries;', sql)
    self.assertIn('DELETE FROM quizzes;', sql)
    self.assertLess(sql.index('DELETE FROM push_deliveries;'), sql.index('DELETE FROM quizzes;'))

  def test_down_sql_clears_deliveries_for_seeded_ids(self) -> None:
    sql = build_down_sql([sample_quiz(7)], 'quizzes.json')
    self.assertIn('DELETE FROM push_deliveries WHERE quiz_id IN (7);', sql)
    self.assertIn('DELETE FROM quizzes WHERE id IN (7);', sql)

  def test_helper_keeps_dependent_rows_first(self) -> None:
    lines = delete_replaced_quiz_rows_sql('9')
    self.assertEqual(lines[0], 'DELETE FROM push_deliveries WHERE NOT (quiz_id = ANY(ARRAY[9]::bigint[]));')
    self.assertEqual(lines[1], 'DELETE FROM quizzes WHERE NOT (id = ANY(ARRAY[9]::bigint[]));')


if __name__ == '__main__':
  unittest.main()
